# Generated by Django 3.2.18 on 2023-04-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(default='profile_pics/empty_user.jpg', upload_to='profile_pics/')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
