# Generated by Django 3.2.18 on 2023-04-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='followed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='followed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profiles.profile'),
        ),
    ]
