# Generated by Django 3.2.18 on 2023-04-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
