# Generated by Django 4.1.7 on 2023-03-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to='posts/%Y/%m/%d/'),
        ),
    ]
